### ISSUE TITLE
Scan operation is performed even when a valid GSI exists for the query

### ISSUE THREAD

**Issue by prasanna0586** [boostchicken/spring-data-dynamodb#21]
## Expected Behavior
Lets say I have a documents table with document_id of type String as HASH_KEY.
I have created a GSI for that table with department_id (of type Number) as HASH KEY and category_id (of type Number) as RANGE KEY

So a department can have multiple documents and each document has one document category.

My repository looks like this:

public interface DepartmentIdCategoryIdRepository
        extends PagingAndSortingRepository<DocumentMetadata, DepartmentIdCategoryId> {

List<DocumentMetadata> findAllByDepartmentIdAndCategoryIdIn(Integer departmentId, List<Integer> categoryId);
}

DepartmentIdCategoryId is composite GSI (department_id HASH and category_id RANGE) as mentioned above

When I invoke findAllByDepartmentIdAndCategoryIdIn a scan operation is being performed.

As a valid GSI exists for the above find operation, scan should not be performed and hence @EnableScan is not required

This issue is similar to -> https://github.com/derjust/spring-data-dynamodb/issues/162

## Actual Behavior

I am getting the below error:

java.lang.IllegalArgumentException: Scanning for this query is not enabled.  To enable annotate your repository method with @EnableScan, or enable scanning for all repository methods by annotating your repository interface with @EnableScan

## Steps to Reproduce the Problem

  1. Create a dynamodb table with document_id  as HASH_KEY
  2. Create a GSI with department_id as HASH_KEY and category_id as RANGE_KEY
  3. Define a find method in the repository querying the GSI with document_id hash key and list of category_id range key (IN clause)

## Specifications
  
  - Spring Boot Version: 2.2.5.RELEASE
  - Spring Data DynamoDB Version: 5.2.3
  - Spring Data Version: Moore-SR5
  - AWS SDK Version: 1.11.415
  - Java Version: 8
  - Platform Details: Windows 10 64bit

All those information are logged by `org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory` on `INFO` level on startup.
Or use `java -version` and `mvn dependency:tree | grep -E 'spring|aws'` to provide those version numbers.

Log for reference:

java.lang.IllegalArgumentException: Scanning for this query is not enabled.  To enable annotate your repository method with @EnableScan, or enable scanning for all repository methods by annotating your repository interface with @EnableScan
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.socialsignin.spring.data.dynamodb.query.MultipleEntityScanExpressionQuery.assertScanEnabled(MultipleEntityScanExpressionQuery.java:41) ~[spring-data-dynamodb-5.2.3.jar:5.2.3]
	at org.socialsignin.spring.data.dynamodb.query.MultipleEntityScanExpressionQuery.getResultList(MultipleEntityScanExpressionQuery.java:36) ~[spring-data-dynamodb-5.2.3.jar:5.2.3]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$CollectionExecution.execute(AbstractDynamoDBQuery.java:104) ~[spring-data-dynamodb-5.2.3.jar:5.2.3]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:311) ~[spring-data-dynamodb-5.2.3.jar:5.2.3]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618) ~[spring-data-commons-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at com.sun.proxy.$Proxy119.findAllByDepartmentIdAndCategoryIdIn (Unknown Source) ~[na:na]
	at com.lmig.gs.surety.docmgmt.metadata.agency.controller.DepartmentMetadataController.getAllByDepartmentId(DepartmentMetadataController.java:110) ~[classes/:na]

**Comment by boostchicken** [comment]
@prasanna0586 did you update your Model Object to have the GSI defined via annotations?  This is done using @DynamoDBIndexRangeKey and @DynamoDBIndexHashKey

`@DynamoDBIndexHashKey(globalSecondaryIndexNames = {"your-index-name"})`

**Comment by boostchicken** [comment]
Hey @prasanna0586 

I dug through the source code and found why this does not work.  DynamoDB does not let you limit based on two fields.  Hence, the source code disallows it as well.  Please see this for more details.

https://aws.amazon.com/blogs/database/querying-on-multiple-attributes-in-amazon-dynamodb/

**Comment by prasanna0586** [comment]
> @prasanna0586 did you update your Model Object to have the GSI defined via annotations? This is done using @DynamoDBIndexRangeKey and @DynamoDBIndexHashKey
> 
> `@DynamoDBIndexHashKey(globalSecondaryIndexNames = {"your-index-name"})`

Yes, I did. The Global secondary index hash and Range were properly defined with its index hash and range key annotations.

**Comment by prasanna0586** [comment]
> Hey @prasanna0586
> 
> I dug through the source code and found why this does not work. DynamoDB does not let you limit based on two fields. Hence, the source code disallows it as well. Please see this for more details.
> 
> https://aws.amazon.com/blogs/database/querying-on-multiple-attributes-in-amazon-dynamodb/

I did see that when I was digging through. I then started taking the approach below. However, the reason behind this issue is why will spring data dynamodb not be able to generate a query like this automatically when I define a method like findByDepartmentIdAndCategoryIdIn(Integer departmentId, List<Integer> categoryId)? Please see details below:

I was able to get it to work by using a custom repository (that inherits from a repository which has the department _id GSI hash key and date_created as RANGE key. You can also do this without a range key defined. However I needed that for sorting. Note: this repository does not have a Range key for category _id)

Then I built the query:

        dynamoDBQueryExpression.withIndexName("idx_global_department_id")
                               .withKeyConditionExpression("department_id = :departmentId")
                               .withFilterExpression(filterAttributeName + " IN (" + String.join(",", categoryIdList) +")")
                               .withScanIndexForward(false)
                               .withConsistentRead(false)
                               .withExpressionAttributeValues(expressionAttributeValues);

        return dynamoDBMapper.query(DocumentMetadata.class, dynamoDBQueryExpression);

Here categoryIdList is a comma separated list of category_id and withScanIndexForward(false) sorts the results in descending order (by range key which is date_created in this case).

I used https://github.com/derjust/spring-data-dynamodb/wiki/Custom-repository-implementations as reference.
