### ISSUE TITLE
Multiple methods annotated by @DynamoDBRangeKey

### ISSUE THREAD

**Issue by sbose-altimetrik** [boostchicken/spring-data-dynamodb#517]
I was trying out spring-data-dynamodb Implementation with @DynamoDbHashKey & @DynamoDBRangeKey in the format which is specified at https://medium.com/@leohoc/dynamodb-and-spring-data-a81c546a1305

But the application is failing on startup with the error:
```
Multiple methods annotated by @DynamoDBRangeKey within type com.service.EntityClass!
        at org.springframework.util.Assert.isNull(Assert.java:162)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBHashAndRangeKeyMethodExtractorImpl$3.doWith(DynamoDBHashAndRangeKeyMethodExtractorImpl.java:79)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:364)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:343)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBHashAndRangeKeyMethodExtractorImpl.<init>(DynamoDBHashAndRangeKeyMethodExtractorImpl.java:75)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBHashAndRangeKeyExtractingEntityMetadataImpl.<init>(DynamoDBHashAndRangeKeyExtractingEntityMetadataImpl.java:45)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBEntityMetadataSupport.getEntityInformation(DynamoDBEntityMetadataSupport.java:123)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getEntityInformation(DynamoDBRepositoryFactory.java:104)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getDynamoDBRepository(DynamoDBRepositoryFactory.java:128)
        at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getTargetRepository(DynamoDBRepositoryFactory.java:150)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:310)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297)
        at org.springframework.data.util.Lazy.getNullable(Lazy.java:211)
        at org.springframework.data.util.Lazy.get(Lazy.java:95)

```
## Specifications
  
  - Spring Data DynamoDB Version:  5.2.5 (2.2)
  - Spring Data Version: 2.3.6.RELEASE
  - AWS SDK Version: 1.11.943
  - Java Version: 1.8.0_282 - OpenJDK 64-Bit Server VM 25.282-b08
  - Platform Details: Linux 3.10.0-1160.49.1.el7.x86_64

**Comment by sbose-altimetrik** [comment]
@boostchicken - Please help on this issue
